site_name: 小黄鸭
site_author: Yanghualv
site_url: https://example.com/
nav:
  - Home: 
    - index.md
    - 疑问: Home/answer.md

  - 开发文档: 
    - concept2:
      - 项目摘要: Documentation/concept2/c2_index.md
      - 构建命令: Documentation/concept2/concept2.md
    - 测试目录:
      - 测试: Documentation/test/test.md

  - 笔记:
    - study_notes: 
      - faster-rcnn: Documentation/study_notes/faster-rcnn/faster-rcnn-学习笔记.md


theme:
  name: material
  logo: Icon/home_icon.gif

  icon:
    # 更改页脚中的导航箭头
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - scheme: default # 日间模式
      primary: blue# 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - git-revision-date-localized
    - minify:
      minify_html: true
  features:  
    - navigation.footer #页脚可以包含指向当前页面的上一页和下一页的链接
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 复制按钮
  language: zh # 一些提示性的文字会变成中文

  custom_dir: overrides


markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
      hljs_languages:
        c: c
        cpp: cpp
        python: python
        javascript: javascript
        # 添加其他需要的语言

extra_css:
  - extra.css

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
  - extra.js



# 仓库信息
repo_url: https://github.com/yanghualv7/yanghualv7.github.io
repo_name: yanghualv7的个人网站

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yanghualv7
      name: GitHub

    - icon: fontawesome/solid/paper-plane
      link: mailto:yang2652841696@gmail.com
      name: Google
  analytics:
    provider: google
    property: G-K58VQQYH80
    disqus: 'something'

copyright: Copyright &copy; 2023 - NULL yanghualv
