site_name: 小黄鸭
site_author: Yanghualv
site_url: https://example.com/

theme:
  name: material
  logo: Icon/home_icon.gif

  icon:
    # 更改页脚中的导航箭头
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - scheme: default # 日间模式
      primary: blue# 上方的
      accent: cyan # 链接等可交互元件的高亮色1
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - git-revision-date-localized
    - minify:
      minify_html: true
  features:  
    - navigation.footer #页脚可以包含指向当前页面的上一页和下一页的链接
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - content.code.copy # 复制按钮
  language: zh # 一些提示性的文字会变成中文

  custom_dir: overrides

markdown_extensions:
  - admonition  # 提示、注意事项、警告等注解框
  - codehilite:  # 代码高亮
      guess_lang: false 
      hljs_languages:
        c: c
        cpp: cpp
        python: python
        javascript: javascript
        # 添加其他需要的语言
  - def_list  # 定义列表
  - footnotes  # 脚注
  - meta  # 元数据
  - toc:  # 目录
      permalink: true  # 目录链接
  - pymdownx.arithmatex:  # LaTeX 数学公式
      generic: true
  - pymdownx.caret  # 上标
  - pymdownx.critic  # 批注和评论
  - pymdownx.details  # 可折叠的细节块
  - pymdownx.emoji:  # Emoji 表情符号
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite  # 内联代码高亮
  - pymdownx.keys  # 按键和快捷键
  - pymdownx.magiclink  # 自动链接转换
  - pymdownx.mark  # 标记（mark）文本
  - pymdownx.smartsymbols  # 特殊字符和符号转换
  - pymdownx.superfences  # 自定义代码块语法
  - pymdownx.tasklist:  # 任务列表
      custom_checkbox: true
  - pymdownx.tilde  # 删除线

extra_css:
  - extra.css
  
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - '//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js'
  - extra.js



# 仓库信息
repo_url: https://github.com/yanghualv7/yanghualv7.github.io
repo_name: yanghualv7的个人网站

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yanghualv7
      name: GitHub

    - icon: fontawesome/solid/paper-plane
      link: mailto:yang2652841696@gmail.com
      name: Google
  analytics:
    provider: google
    property: G-K58VQQYH80

copyright: Copyright &copy; 2023 - NULL yanghualv

nav:
  - Home: 
    - index.md
    - 疑问: Home/answer.md
    - 待做事项: Home/todo.md

  - 开发文档: 
    - concept2:
      - 项目摘要: Documentation/concept2/c2_index.md
      - 构建命令: Documentation/concept2/concept2.md
  - Git:
    - git操作总结:
      - 前言: Documentation/git/git-index.md
      - git推送: Documentation/git/git-推送方式.md
      - git克隆项目失败: Documentation/git/git-小细节.md

  - 笔记:
    - study-notes: 
      - faster-rcnn: Documentation/study-notes/faster-rcnn/faster-rcnn-学习笔记.md
      - 计算机系统基础笔记: Documentation/study-notes/computer-system-basic/计算机系统基础笔记.md
    - mkdocs操作:
      - 添加评论功能: Documentation/study-notes/mkdocs/mkdocs-添加评论功能.md
    - vscode操作:
      - python环境切换: Documentation/study-notes/vscode/vscode-python-环境切换.md
      - C/C++环境配置: Documentation/study-notes/vscode/vscode-CC++环境配置.md
